### ISSUE TITLE
Website 502

### ISSUE THREAD

**Issue by maltewhiite** [jorgelbg/dissect-tester#26]
I tried going to: https://dissect-tester.jorgelbg.me/

I found the website via this article: https://jorgelbg.me/2020/02/web-ui-for-testing-dissect-patterns/

I really need some way to debug my dissect stuff easily, and this was exactly what I was looking for. Quite sad it is down. Please get it online :) 

![image](https://user-images.githubusercontent.com/90693329/136227522-78d4c96a-f970-407d-b232-386eab1767ad.png)

**Comment by jorgelbg** [comment]
Hi @maltewhiite thanks for the report! 
I'm happy to report that https://dissect-tester.jorgelbg.me/ is up and running again. Sorry for the delay, apparently my provider had an unexpected issue with the VM 😅.
